blank_issues_enabled: true
contact_links:
  - name: Namseokcoin Core Security Policy
    url: https://github.com/namseokcoin/namseokcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Namseokcoin Core Developers
    url: https://namseokcoincore.org
    about: Namseokcoin Core homepage
